import type { Article } from '../types';

/* ============================================================================
   heatt Originals — pre-loaded long-form library.
   Written for the platform, stored as structured blocks so the reader renders
   natively with zero external requests: nothing missing, no redirects.
   ==========================================================================*/

export const ORIGINALS: Article[] = [
  {
    id: 'orig-heat-diffusion',
    kind: 'forge',
    title: 'Heat Diffusion: ranking a feed like a cooling body',
    dek: 'Chronology buries good writing. Popularity entrenches it. A thermodynamic ranker does neither — it just measures who is still burning.',
    author: 'k-vasiliev',
    tags: ['algorithms', 'ranking', 'feeds'],
    cover: '/art/shader-flames.jpg',
    accent: '#FFB454',
    date: '2026-09-18T09:12:00Z',
    minutes: 11,
    reactions: 1840,
    comments: 132,
    hot: true,
    blocks: [
      { t: 'p', text: 'Every feed is a lie about time. Chronological feeds pretend the world is flat: a brilliant essay from Tuesday sits under a mediocre take from Wednesday. Popularity feeds pretend the world is finished: the winner keeps winning because it already won. Neither model is *about* the reader.' },
      { t: 'p', text: 'We built **Heat Diffusion** to answer a narrower question: *what is still actively burning right now?* That single reframe kills most of the tuning problems, because it turns ranking into a physics simulation with two terms — energy injected by engagement, and energy lost to cooling.' },
      { t: 'h', text: '1. Injection: not all heat is equal', id: 'injection' },
      { t: 'p', text: 'A tap is cheap. A two-second hold is a decision. So engagement is not a counter, it is a **level**, and levels are weighted super-linearly:' },
      { t: 'code', lang: 'ts', caption: 'lib/heat.ts — weights', code: [
        'export const K = {',
        '  heatW:   [0, 1, 2.6, 6.5], // tap → hold → hold-to-3',
        '  saveW:   1.3,              // intent to return',
        '  shareW:  2.2,              // heat exported off-platform',
        '  replyW:  1.15,             // conductance',
        '  tau:     9,                // Newton cooling, hours',
        '};',
      ].join('\n') },
      { t: 'p', text: 'The multipliers matter less than their *ratios*. Level 3 is 6.5× a tap — enough that a handful of deliberate ignitions can outrank a hundred idle taps, but not enough that a coordinated burst can buy the front page.' },
      { t: 'h', text: '2. Thermal mass: reputation as a conductor', id: 'mass' },
      { t: 'p', text: 'A read from someone whose engagement history predicts reads by others is worth more than a bot read. We attach a scalar to each reader — *thermal mass* — from three observable, non-gaming quantities:' },
      { t: 'ol', items: [
        '**Read-through rate** — do they finish what they heat?',
        '**Reply quality** — replies that themselves receive heat (recursive, damped).',
        '**Heat decay honesty** — users who un-heat things they abandon carry less mass than users who never cool.',
      ] },
      { t: 'code', lang: 'ts', code: [
        'const injected = (local + read + saved + shared) * mass;',
        'const conduct  = K.kappa * Math.log1p(crowd) * (mass - 1) * 0.35;',
        'const temp     = crowd + injected + conduct;',
      ].join('\n') },
      { t: 'p', text: 'Note that reputation modulates the *reader*, not the author. We refuse to build a follower-count ranking: it converts an audience into a toll booth and a new account into a ghost.' },
      { t: 'h', text: '3. Cooling: Newton was a feed engineer', id: 'cooling' },
      { t: 'quote', text: 'The rate of heat loss of a body is proportional to the difference in temperatures between the body and its surroundings.', cite: 'Isaac Newton, 1701' },
      { t: 'p', text: 'Applied to a post, this is the boring, correct answer to staleness: `T(t) = T₀ · e^(−t/τ)`. No half-life tables, no "top of the month" pages rotting for 30 days. We run two clocks — a slow τ for total temperature and a fast τ for *velocity* — and rank by `log(1+T) · (1+velocity)^0.55`.' },
      { t: 'callout', kind: 'heat', title: 'Why log, not linear', text: 'Linear scoring turns ranking into an arms race of volume. log(1+T) compresses the top of the distribution so a 10× spike in reactions moves rank, but never drowns the board.' },
      { t: 'h', text: '4. Semantic cliff truncation', id: 'cliff' },
      { t: 'p', text: 'The last piece is truncation, and it is where we differ from every "top" tab on the internet. We sort the candidate logits, then look for the steepest *local* drop with a position-weighted penalty. Everything past the cliff is demoted — not shown lower, but not shown at all on the For-You board.' },
      { t: 'code', lang: 'ts', caption: 'Finding the cliff — 12 lines', code: [
        'for (let i = 3; i < n - 2; i++) {',
        '  const gap   = logits[i - 1] - logits[i];',
        '  const slope = logits[1] - logits[0];',
        '  const weighted = gap / (Math.abs(slope) + 1e-6) - 0.02 * i;',
        '  if (weighted > best) { best = weighted; idx = i; }',
        '}',
        'return Math.max(4, Math.min(n, idx + 1));',
      ].join('\n') },
      { t: 'p', text: 'The result: on a quiet morning you get eight genuinely hot items and no filler. On a loud one you get thirty. The feed has a *shape*, and the shape carries information — which is precisely what the infinite scroll destroyed.' },
      { t: 'h', text: '5. What we measured', id: 'measure' },
      { t: 'ul', items: [
        'Median read-through of syndicated articles: **18% → 41%** after heat weighting.',
        'Time-to-first-reply on new authors: **−62%** (cooling favours fresh, so newcomers get seen).',
        'Tap-out rate in the first 30 seconds: **−24%**; heat holds ≥2 rose to 31% of all heats.',
      ] },
      { t: 'p', text: 'None of this is exotic maths. It is two exponential decays, a log, and the discipline to cut off the tail. The exotic part is the assumption underneath: that attention is energy, and energy is finite, and a feed that forgets that is just a landfill with a search box.' },
      { t: 'links', items: [
        { label: 'Newton’s law of cooling', href: 'https://en.wikipedia.org/wiki/Newton%27s_law_of_cooling', note: 'the one-line model behind τ' },
        { label: 'Hacker News ranking (time-decay comparison)', href: 'https://albertz.github.io/hacker-news-ranking/', note: 'the classic 12h half-life' },
        { label: 'reddit/ranking — hot ordering', href: 'https://github.com/reddit-archive/reddit/blob/master/r2/r2/lib/db/_sorts.py', note: 'log-confidence + age' },
      ] },
    ],
  },
  {
    id: 'orig-dark-material',
    kind: 'forge',
    title: 'Graphite rooms: designing in the dark without losing depth',
    dek: 'Black backgrounds are easy. Black interfaces with real hierarchy and zero eye strain are not. A field guide to dark-first design systems.',
    author: 'nyra',
    tags: ['design', 'dark-ui', 'color'],
    cover: '/art/molten-ui.jpg',
    accent: '#63D8F5',
    date: '2026-09-16T14:40:00Z',
    minutes: 9,
    reactions: 2410,
    comments: 186,
    hot: true,
    blocks: [
      { t: 'p', text: 'The most common dark-mode failure is not contrast. It is *flatness*. Designers take a light system, invert it, and end up with a UI where every surface is the same weight — because the thing that carried hierarchy was never colour, it was shadow, and shadow does not survive on black.' },
      { t: 'h', text: 'Keep the steps visible' },
      { t: 'p', text: 'heatt’s room is true black (`#000000`), and everything you actually read sits above it: base `#050505`, panel `#121212`, elevated `#1A1A1A`, lift `#1E1E1E`. Four steps, a couple of percent of luminance apart, and the interface still reads instantly at arm’s length. Why?' },
      { t: 'ul', items: [
        'The room can be `#000` because nothing is drawn on it directly. Surfaces that carry text stop at `#050505`–`#1E1E1E`, where white text keeps its halation in check instead of blooming into a 21:1 void.',
        'An accent that bleeds into true black looks like a smudge; the same accent on a `#121212` panel looks like light.',
        'Elevation must remain expressible. On black, `box-shadow` is dead; on charcoal, it is a material.',
      ] },
      { t: 'h', text: 'Heat as a semantic colour, not a decoration' },
      { t: 'p', text: 'Every accent in heatt is temperature. `#FFB454` is not a brand colour — it is what heat looks like on a cold surface, and the ramp is continuous into the UI: hover states lift the border, focus rings catch the light, the reading progress bar brightens as you descend. Colour stops being fashion and starts being *information*.' },
      { t: 'code', lang: 'css', caption: 'the ramp is the system', code: [
        ':root {',
        '  --ht-cryo-teal: #63d8f5; /* counterweight: cool = new  */',
        '  --ht-jade:      #efcb8b; /* held, kept, verified */',
        '  --ht-ember:     #ffb454; /* level 2 — the signal */',
        '  --ht-flame:     #f59a2b; /* level 3  */',
        '  --ht-magma:     #ffc978; /* ignition */',
        '  --ht-whitehot:  #fff6e8; /* 100% read */',
        '}',
      ].join('\n') },
      { t: 'p', text: 'The interesting constraint is restraint. One accent, used only where something is actually happening, reads as *signal*. The same accent sprayed across cards, borders and backgrounds reads as decoration — and decoration is what makes a dark UI look cheap. We reserve teal and soft indigo for *cold* states: unread, new, unranked, draft. Warm means "something is happening to this object". Cool means "nothing has yet". Once you commit to that, you can’t accidentally decorate — every glow has to mean something.' },
      { t: 'h', text: 'A room needs to be a room' },
      { t: 'p', text: 'The frosted-panel trick (backdrop-filter, 1px inner highlight, saturate the blur) is everywhere, and in most apps it is a lie: you cannot see through a blurred sheet of nothing. Blur only communicates depth when there is *something behind it worth obscuring*. So the shell sits on a near-black room with two very soft light sources and a faint grid — still enough to refract, quiet enough that you stop noticing it, which is the whole point.' },
      { t: 'callout', kind: 'warn', title: 'One perf caveat', text: 'Every blurred surface costs a compositor pass. Cap the blur radius (18px), keep blurred surfaces few (≤6 on screen), and stop animating anything behind them while a modal is open — the refracted light you get for free is not worth a dropped frame on a low-end phone.' },
      { t: 'h', text: 'Motion budget' },
      { t: 'p', text: 'We hold the interface to 400ms for anything that responds to a click and 180ms for anything that is a direct consequence of one. Entrances can be slower and use a long out-expo; exits must be faster than entrances, always. The one place we break the rules is ignition: 2.4 seconds of fire is *intentionally* unresponsive, because the reward for a deliberate hold is a moment, not a transition.' },
      { t: 'p', text: 'Dark design systems are not about darkness. They are about the small number of light sources you allow to exist, and being merciless about why each one is there.' },
      { t: 'links', items: [
        { label: 'Material Design dark theme guidance', href: 'https://m2.material.io/design/color/dark-theme.html', note: 'elevation overlays on dark' },
        { label: "Apple — Dark Mode (Human Interface)", href: 'https://developer.apple.com/design/human-interface-guidelines/dark-mode', note: 'layering with 28% white' },
        { label: 'WCAG APCA (contrast for dark UI)', href: 'https://readtech.org/ARC/tests/visual-color-contrast/apca/', note: 'why 4.5:1 lies at low luminance' },
      ] },
    ],
  },
  {
    id: 'orig-fluid-type',
    kind: 'forge',
    title: 'Cold type, warm reading: a fluid typography system',
    dek: 'Breakpoints make typography snap. clamp() makes it breathe — and gets you 65 characters per line on every device you will ever ship against.',
    author: 'amara',
    tags: ['typography', 'css', 'reading'],
    cover: '/art/cold-type.jpg',
    accent: '#F59A2B',
    date: '2026-09-14T07:30:00Z',
    minutes: 8,
    reactions: 1320,
    comments: 94,
    blocks: [
      { t: 'p', text: 'Reading is the product. Everything else — the feed, the heat, the graph — is a hallway to an article. So the typography system is the one place we refuse to be clever.' },
      { t: 'h', text: 'One function, four tokens' },
      { t: 'p', text: 'heatt defines its whole scale with `clamp()` — a minimum, a viewport-proportional slope, and a maximum. No media queries exist for type at all; the scale is continuous, so the interval between steps stays perceptually constant as the viewport grows.' },
      { t: 'code', lang: 'css', code: [
        ':root {',
        '  --fs-base: clamp(0.95rem, 0.9rem + 0.24vw, 1.075rem);',
        '  --fs-lg:   clamp(1.1rem, 1rem   + 0.5vw,  1.35rem);',
        '  --fs-xl:   clamp(1.35rem, 1.15rem + 0.95vw, 1.95rem);',
        '  --fs-hero: clamp(2.9rem, 1.4rem + 7.4vw, 7.6rem);',
        '}',
      ].join('\n') },
      { t: 'p', text: 'The hero slope is 7.4vw — deliberately violent, because display type should feel like it belongs to the viewport. Body slope is 0.24vw, almost none, because a paragraph that grows 15% between a phone and a 32" monitor becomes a chore: line length wins over size.' },
      { t: 'h', text: 'Measure before size' },
      { t: 'p', text: '65–75 characters per line is the range every serious study of reading comfort lands on, and we hit it by constraining the *column*, not by picking a font size:' },
      { t: 'code', lang: 'css', code: ['article { max-inline-size: 68ch; margin-inline: auto; }'].join('\n') },
      { t: 'p', text: 'With `68ch` as the constraint, resizing the type on desktop does not create longer lines — it creates *taller* paragraphs, which is exactly what a reader wants when they say "make it bigger". That single decision removed our entire accessibility-settings backlog.' },
      { t: 'h', text: 'Two families, strictly typed roles' },
      { t: 'ul', items: [
        '**Display (Bricolage Grotesque)** — headlines, feed chrome, buttons. Optical, tight tracking at `-0.03em`.',
        '**Read (Newsreader)** — long-form body. High contrast, generous x-height, italic that is a real italic.',
        '**Code (JetBrains Mono)** — 0.83em inside prose, never smaller, never justified.',
      ] },
      { t: 'p', text: 'A variable font is not a performance trick here; it is a *weight budget*. We use one file and interpolate `wght` for the 3–4 weights the system needs, rather than shipping four static cuts the way sites did in 2015.' },
      { t: 'h', text: 'The details that make 2am readable' },
      { t: 'ol', items: [
        'Line-height 1.78 at body size, tightening to 1.14 for headings — the inverse of what most systems do.',
        'Warm off-white ink (`#EFEDEA`) on near-black, never pure white: cuts halation by a third at equal perceived contrast.',
        '`text-wrap: balance` on headlines, `pretty` on paragraphs — orphan control for free.',
        'Paragraph spacing derived from the same clamp() token, so rhythm scales with size.',
      ] },
      { t: 'callout', kind: 'note', title: 'Reader controls we ship', text: 'Three densities (dense / normal / cozy), column width, serif↔sans toggle, and a warm filter for night. Every control writes to one attribute on <html> — CSS owns the rest, React never re-renders for typography.' },
      { t: 'p', text: 'Fluid typography is not a trick to avoid breakpoints. It is a commitment that the reader’s device is not your problem to categorise — only your problem to serve.' },
      { t: 'links', items: [
        { label: 'Fluid typography with CSS clamp', href: 'https://piccalil.li/blog/fluid-typography-with-css-clamp/', note: 'the slope/min/max method' },
        { label: 'text-wrap: balance & pretty', href: 'https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap', note: 'MDN' },
        { label: 'Read — typographic long-form study', href: 'https://read.tech', note: 'reading comfort research' },
      ] },
    ],
  },
  {
    id: 'orig-cold-start',
    kind: 'forge',
    title: 'The zero-dollar cold start: syndicating a feed without scraping',
    dek: 'A new social app has an empty-room problem. Paying for content is one answer. The better one is a public API, a renderer you own, and honest attribution.',
    author: 'tobi',
    tags: ['architecture', 'api', 'growth'],
    cover: '/art/ember-signal.jpg',
    accent: '#EFCB8B',
    date: '2026-09-12T11:05:00Z',
    minutes: 10,
    reactions: 980,
    comments: 71,
    blocks: [
      { t: 'p', text: 'Nobody joins an empty network. Every social launch solves this the same way: seed it with your own writing, or quietly hire a content team, or borrow a trending feed and pray nobody notices. heatt took a fourth path — the open, documented, *permitted* route: the Forem (Dev.to) REST API, which returns full article payloads to unauthenticated clients.' },
      { t: 'h', text: 'Why an API and not an RSS scrape' },
      { t: 'ul', items: [
        '`GET /api/articles` returns structured JSON: author object, cover image, tags, reaction counts, reading time, canonical URL. No HTML heuristics that break on the next redesign.',
        'It is rate-limited and *documented*, which means we can design around it instead of being banned by it.',
        'Bodies come back as Markdown via `GET /api/articles/{id}` — so we render in our own typography, and the reader never leaves the app.',
      ] },
      { t: 'code', lang: 'ts', caption: 'server route with SWR headers', code: [
        'export const revalidate = 600;',
        '',
        'export async function GET(req: Request) {',
        '  const url = new URL("https://dev.to/api/articles");',
        '  url.searchParams.set("per_page", "30");',
        '  url.searchParams.set("top", "7");',
        '  const r = await fetch(url, { next: { revalidate: 600 } });',
        '  return new Response(r.body, {',
        '    headers: {',
        '      "content-type": "application/json",',
        '      "cache-control": "s-maxage=600, stale-while-revalidate=86400",',
        '    },',
        '  });',
        '}',
      ].join('\n') },
      { t: 'p', text: 'One origin fetch every ten minutes serves an unlimited number of readers, because the CDN holds the response while it is *stale* and revalidates in the background. Our entire content pipeline costs roughly $0/month until it costs something for other reasons.' },
      { t: 'h', text: 'The licence question, answered honestly' },
      { t: 'p', text: 'Syndication is where most "reader" apps quietly become thieves. We made three rules and put them in code, not in a policy PDF:' },
      { t: 'ol', items: [
        'The article is displayed with an **attribution card**: author, org, original publication date, and a visible "Read original" link that opens in a new tab.',
        '**No body text is stored** in our database or bundled in the app. Markdown is fetched per read and cached ephemerally for 24h so return visits are fast — and that cache is cleared by a single user action.',
        'Heat on heatt is additive, not extracted: every engagement counter on a syndicated piece is public on the origin too.',
      ] },
      { t: 'callout', kind: 'heat', title: 'Why this helps the author', text: 'Our readers heat the piece on *our* graph, the ranking boost is computed from real read-throughs, and the author keeps the canonical URL and the follow link. Discovery and credit are the same feature.' },
      { t: 'h', text: 'Rendering pipeline' },
      { t: 'p', text: 'Markdown arrives as text. We normalise it through `unified`: `remark-parse` → `remark-gfm` (tables, footnotes, task lists) → `rehype-raw` for the HTML embeds Dev.to allows → `rehype-sanitize` with a strict allowlist → `rehype-highlight` for code. Then we render to React elements rather than `dangerouslySetInnerHTML`, which lets our own components own images, links and code blocks.' },
      { t: 'ul', items: [
        '**Images** become lazy, aspect-ratio-reserved, and get a heat-shimmer placeholder — no layout shift.',
        '**Links** to other syndicated pieces route *inside* heatt; everything else opens in a new tab with `rel="noopener noreferrer"`.',
        '**Code** gets a copy button, a language chip, and a wrap toggle for the 120-column monsters.',
      ] },
      { t: 'h', text: 'What it does not solve' },
      { t: 'p', text: 'Syndication gives you a library, not a community. Reader conversion is real, but reply rate on borrowed content is near zero — people do not argue with an article they cannot follow. That is why the syndicated feed is interleaved with sparks: the borrowed material earns attention, and the local material converts it into a network. Feed composition, not feed volume, is the cold-start fix.' },
      { t: 'links', items: [
        { label: 'Forem (Dev.to) public API docs', href: 'https://developers.forem.com/api', note: 'the unauthenticated endpoints' },
        { label: 'unified: remark & rehype', href: 'https://unifiedjs.com', note: 'the Markdown pipeline' },
        { label: 'MDN: Cache-Control stale-while-revalidate', href: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control', note: 'the whole trick in one directive' },
      ] },
    ],
  },
  {
    id: 'orig-heatmaps',
    kind: 'forge',
    title: 'Heatmaps people stare at: motivation without shame',
    dek: 'The contribution grid is the most persuasive UI element on the internet, and the most easily turned into a guilt machine. Five rules.',
    author: 'sena',
    tags: ['habits', 'gamification', 'data-viz'],
    cover: '/art/graphite-lattice.jpg',
    accent: '#FFE3B0',
    date: '2026-09-10T16:20:00Z',
    minutes: 7,
    reactions: 1610,
    comments: 118,
    blocks: [
      { t: 'p', text: 'A grid of squares, one per day, coloured by intensity. GitHub proved it can move millions of people to show up daily. Duolingo proved the same mechanism can make people feel watched by an owl. The visualisation is identical; the *relationship* is completely different.' },
      { t: 'h', text: 'Rule 1 — Colour encodes volume, never absence' },
      { t: 'p', text: 'Five steps: `transparent → ember → flame → magma → whitehot`. A zero-activity day must stay visually quiet. The moment empty cells are *coloured* (grey blocks, red gaps), the eye stops reading intensity and starts reading failure — and users who read failure avoid the page.' },
      { t: 'h', text: 'Rule 2 — The streak is a promise, not a punishment' },
      { t: 'p', text: 'heatt shows a streak, but recovering one costs nothing and breaks nothing: the counter keeps the **best current run** and shows *paused* days as neutral. Behaviourally, loss framing dominates gains — so if a mechanic can hurt, and you keep the hurt, you have chosen a dark pattern on purpose.' },
      { t: 'h', text: 'Rule 3 — Every cell must answer "what happened"' },
      { t: 'p', text: 'Tap a cell and you get the day: three articles read, one forge published, a spark that hit level-3 ignition at 21:14, 41 minutes of reading. Data that cannot be interrogated is decoration; data that tells you what you *did* is memory. Memory is what makes people come back.' },
      { t: 'code', lang: 'ts', caption: 'aggregated daily log — one indexed query', code: [
        'type HeatLog = {',
        '  day: string;        // "2026-09-10" — relational, B-Tree indexed',
        '  reads: number;',
        '  forges: number;',
        '  sparks: number;',
        '  ignitions: number;  // level-3 heats received',
        '  minutes: number;',
        '  events: { at: number; kind: string; ref: string }[];',
        '};',
      ].join('\n') },
      { t: 'h', text: 'Rule 4 — Show the shape of a week' },
      { t: 'p', text: 'We add a seven-day micro-histogram above the annual grid. People can find their own rhythm — "I read on weekdays, I write on Sundays" — and rhythm is identity. Identity survives a missed Tuesday; a number does not.' },
      { t: 'h', text: 'Rule 5 — Never rank against another person' },
      { t: 'p', text: 'Leaderboards of streak length were the first thing we built and the second thing we deleted (the first was a "1000 days" badge — kept). Comparison inflates the metric and hollows the habit. We compare a reader only to their own trailing 30-day average, and the graph is a private surface by default with a single "share my year" export that renders a story card — because showing someone your year is a *gift*, not a scoreboard.' },
      { t: 'callout', kind: 'note', title: 'Measured effect', text: 'Switching from red gaps to neutral pauses raised 14-day return visits by 9%. Switching from leaderboard to self-average raised them by another 6% and cut badge farming to zero.' },
      { t: 'links', items: [
        { label: 'GitHub contribution graph', href: 'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-profile-settings/viewing-your-contributions', note: 'the original' },
        { label: 'Self-determination theory & gamification', href: 'https://en.wikipedia.org/wiki/Self-determination_theory', note: 'competence, autonomy, relatedness' },
        { label: 'Loss aversion (Kahneman & Tversky)', href: 'https://www.ku.edu/content/prospect-theory-analysis-decision-under-risk', note: 'why red gaps work — and why that is a problem' },
      ] },
    ],
  },
  {
    id: 'orig-ignition',
    kind: 'forge',
    title: 'Ignition: the design of a two-second hold',
    dek: 'A like is a reflex. A heat level is a decision. What happened when we replaced our double-tap with hold-to-intensify.',
    author: 'nyra',
    tags: ['interaction', 'motion', 'research'],
    cover: '/art/story-canvas.jpg',
    accent: '#FFC978',
    date: '2026-09-19T05:15:00Z',
    minutes: 7,
    reactions: 2760,
    comments: 214,
    hot: true,
    blocks: [
      { t: 'p', text: 'Double-tap-to-like has one fatal flaw for a reading product: it is free, so it is worthless as a signal. On heatt, a single tap lights an ember. Holding the button *drives* the interaction — a ring fills around the icon, the card warms, and at two and a half seconds the post catches fire for a beat and a half.' },
      { t: 'h', text: 'The three levels, and why not four' },
      { t: 'ul', items: [
        '**Level 1 — Ember (tap).** "I saw this and it is fine." Cheap, frictionless, honest.',
        '**Level 2 — Blaze (1.15s hold).** "This is good." Requires intent; you must stop scrolling.',
        '**Level 3 — Inferno (2.45s hold).** "This made me change my mind." Full ignition, card burns, and the piece gets a 6.5× thermal injection in the ranker.',
      ] },
      { t: 'p', text: 'We tested a fourth level. It was worse, for a reason we did not expect: past three, users treated it as a *game* to max out and stopped using it as a signal. Three is the last count that reads as judgement rather than score.' },
      { t: 'h', text: 'Making the fire mean something' },
      { t: 'p', text: 'The ignition animation is 2.4 seconds and deliberately not skippable: a shockwave from the button, embers along the card’s bottom edge, a warm bloom on the surface, a one-degree-per-frame wobble of the whole card, then the border cools back down in a visible ramp. It is slow because *you* were slow — the reward mirrors the effort. The one thing we refuse to do is loop it. Fire that loops is a screensaver; fire that ends is an event.' },
      { t: 'code', lang: 'ts', caption: 'hold state machine', code: [
        'onPointerDown: start rAF clock, ring.p = t / 2450',
        '  t ≥ 1150 → level 2  → tick() + card.heat = warm',
        '  t ≥ 2450 → level 3  → ignite():',
        '       vibrate([18, 26, 44]); play fire canvas 2400ms;',
        '       lock level; stop clock',
        'onPointerUp  → commit current level (never overshoot)',
        'onMove > 24px → cancel (scroll intent wins over heat intent)',
      ].join('\n') },
      { t: 'p', text: 'That last line was the hardest. On mobile, a hold that also scrolls is a bug, so scroll intent must always win — which means our pointer handling starts the heat clock *after* the browser decides it is not a scroll, and we lose about 40ms of apparent responsiveness on purpose.' },
      { t: 'callout', kind: 'heat', title: 'Result', text: 'Heats became 71% rarer and 3.4× more predictive of read-through. Our ranker needed fewer heuristics, because the signal stopped lying.' },
      { t: 'p', text: 'Every engagement control is a claim about the effort it costs. Match the reward to the cost and people trust the interface. Break the match and you get a number that everybody ignores.' },
      { t: 'links', items: [
        { label: 'Fitts’ law & hold interactions', href: 'https://en.wikipedia.org/wiki/Fitts%27s_law', note: 'target size vs. time' },
        { label: 'iOS haptic feedback patterns', href: 'https://developer.apple.com/design/human-interface-guidelines/haptics', note: 'impact vs. notification feedback' },
      ] },
    ],
  },
  {
    id: 'orig-deep-read',
    kind: 'forge',
    title: 'Deep reading inside a shallow feed',
    dek: 'The scroll is optimised for leaving. What if the feed were optimised for descending? Notes from two years of building a reader that people finish things in.',
    author: 'amara',
    tags: ['attention', 'reading', 'product'],
    cover: '/art/deep-read.jpg',
    accent: '#B98CFF',
    date: '2026-09-08T18:45:00Z',
    minutes: 9,
    reactions: 1195,
    comments: 143,
    blocks: [
      { t: 'p', text: 'Feeds are engineered for the next item. Reading is the opposite act: staying with one thing until it changes you. Any product that promises both has to answer the boring question nobody asks in a pitch deck — *what does the interface do while someone is reading?*' },
      { t: 'h', text: 'The progress bar is a commitment device' },
      { t: 'p', text: 'A thin line across the top that fills as you descend is not information, it is *obligation*. We measured it: with a progress bar, median read-through rises 12 points; without, the same article, the same readers. The bar does not tell you where you are — it tells you that leaving is visible, and people dislike being visibly unfinished.' },
      { t: 'p', text: 'So we made ours hotter: it starts cool teal at the top and warms to white-hot at 100%. Finishing an article leaves a residue in your heatmap. Leaving mid-way leaves a half-warm line in your library, and you can see it there.' },
      { t: 'h', text: 'Heat waveform: the crowd’s marginalia' },
      { t: 'p', text: 'Every article we syndicate gets a vertical spine on the right — a sparkline of where readers held to level 3. Read it like a seismic chart: a spike near the end means the argument lands late. Flat with one tall peak at paragraph four means a single quotable line is carrying a weak piece.' },
      { t: 'ul', items: [
        'Tap a spike to jump to that paragraph and see the three highest-heated replies anchored there.',
        'Paragraphs with no heat are not hidden — silence is data too.',
        'Authors see their own waveform before publication in draft preview, which changes drafts more than any style guide we have written.',
      ] },
      { t: 'h', text: 'What we removed' },
      { t: 'ol', items: [
        'Related-article blocks inside the text. Reading became "one thing, then decide".',
        'Infinite scroll in the reader. The article ends; the app does not pretend otherwise.',
        'Any comment count inside the body. Discussion lives at the end, behind a fold, never as a nag.',
        'The word "just". "Just save for later" is not a reading interface, it is a landfill with a bookmark icon.',
      ] },
      { t: 'callout', kind: 'warn', title: 'The failure we hit', text: 'We first put the reading-progress bar at the bottom, where keyboards are. On phones it was covered 60% of the time and read-through *fell* 4 points. Position is not aesthetics; on a thumb-scrolled page, the bottom of the viewport is the least-attended pixel in the product.' },
      { t: 'p', text: 'Long-form did not die because attention spans collapsed. It died because interfaces kept interrupting it. Take the interruptions out, add one honest line of progress, and a 2,000-word essay finishes at a rate that would embarrass a newsletter.' },
      { t: 'links', items: [
        { label: 'NNG: How people read on the web', href: 'https://www.nngroup.com/articles/how-little-do-users-read/', note: 'the F-pattern literature' },
        { label: 'Readwise — marginalia as a product', href: 'https://readwise.io', note: 'highlighting as social layer' },
      ] },
    ],
  },
];

export const originalById = new Map(ORIGINALS.map((a) => [a.id, a]));
