import type { Spark } from '../types';

/* ============================================================================
   heatt seed sparks — short-form posts that interleave with the library.
   ==========================================================================*/

export const SPARKS: Spark[] = [
  {
    id: 'sp-01',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-22T04:20:00Z',
    reactions: 4820,
    comments: 214,
    reposts: 610,
    text: 'Reminder of the house rule: heat is a *judgement*, not a click. Tap = ember. Hold = blaze. Hold to three and the thing catches fire, and the piece moves on the board.\n\nIf you max every post you will make your own feed useless. Save the fire.',
    tags: ['meta', 'heat'],
  },
  {
    id: 'sp-02',
    kind: 'spark',
    author: 'nyra',
    date: '2026-09-21T22:11:00Z',
    reactions: 1902,
    comments: 88,
    text: 'Spent the afternoon deleting glows instead of adding them. The interface got better every single time.\n\nDark UI is not about the darkness, it is about how few light sources you can get away with.',
    tags: ['design'],
    media: [{ url: '/art/molten-ui.jpg', alt: 'Frosted panels over a graphite gradient' }],
  },
  {
    id: 'sp-03',
    kind: 'spark',
    author: 'k-vasiliev',
    date: '2026-09-21T18:44:00Z',
    reactions: 1440,
    comments: 62,
    text: 'Heat field update: the ember count is now derived from real temperature instead of a constant, so a cold feed genuinely looks cold. People keep telling me the app is "calmer at 3am". It is not a mood, it is the ranker leaking into the shader.',
    tags: ['webgl', 'engineering'],
  },
  {
    id: 'sp-04',
    kind: 'spark',
    author: 'amara',
    date: '2026-09-21T15:02:00Z',
    reactions: 2360,
    comments: 130,
    text: 'Unpopular: the reading progress bar is not a progress indicator. It is a promise you can see being kept or broken. That is the entire reason read-through went up 12 points when we added it.',
    tags: ['reading', 'typography'],
    longRef: 'orig-deep-read',
  },
  {
    id: 'sp-05',
    kind: 'spark',
    author: 'tobi',
    date: '2026-09-21T09:31:00Z',
    reactions: 812,
    comments: 41,
    text: 'Syndication costs exactly $0/month: one origin fetch every 10 minutes, CDN serves it stale-while-revalidate for 24h. 30k readers, 144 origin hits.\n\nThe "we need a budget for content" meeting should be a "we need an ingestion policy" meeting.',
    tags: ['infra'],
    link: {
      url: 'https://developers.forem.com/api',
      title: 'DEV API (beta) — Introduction | Forem Docs',
      site: 'developers.forem.com',
      desc: 'The public, unauthenticated REST API behind heatt’s long-form library.',
    },
  },
  {
    id: 'sp-06',
    kind: 'spark',
    author: 'sena',
    date: '2026-09-20T21:18:00Z',
    reactions: 1660,
    comments: 96,
    text: 'Red gaps in a streak grid make people avoid the page they are supposed to open. Empty-but-neutral cells make them come back and fix it.\n\n14-day return visits: +9%. Same mechanic, opposite emotion.',
    tags: ['habits', 'research'],
  },
  {
    id: 'sp-07',
    kind: 'spark',
    author: 'marta',
    date: '2026-09-20T13:05:00Z',
    reactions: 402,
    comments: 18,
    text: 'Day 214 of the heatmap. I do not write, I only read and heat things, and I have finished 61 forges this month. This is the first app where a reading habit felt like mine instead of harvested from me.',
    tags: ['reading'],
  },
  {
    id: 'sp-08',
    kind: 'spark',
    author: 'devon',
    date: '2026-09-20T07:44:00Z',
    reactions: 728,
    comments: 34,
    text: 'Hold-to-heat has ruined double-tap for me. I caught myself pressing and *holding* a heart on another app like a caveman.',
    tags: ['interaction'],
  },
  {
    id: 'sp-09',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-19T19:26:00Z',
    reactions: 3110,
    comments: 202,
    reposts: 480,
    text: 'New: Heat Waveform on every long read — the spine on the right shows where readers stopped and held.\n\nSpike near the end = the argument lands late.\nOne tall spike at paragraph four = a quotable line is carrying a weak piece.',
    tags: ['product', 'reading'],
    media: [{ url: '/art/graphite-lattice.jpg', alt: 'Heat grid' }],
    longRef: 'orig-deep-read',
  },
  {
    id: 'sp-10',
    kind: 'spark',
    author: 'k-vasiliev',
    date: '2026-09-19T11:52:00Z',
    reactions: 940,
    comments: 27,
    text: 'The intro is a fragment shader, not a video file. 8.4 seconds, 340KB, plays at 120Hz on a phone, degrades to a static poster on a 2015 laptop. Nobody will ever wait for a 40MB mp4 to load before deciding to stay.',
    tags: ['webgl', 'perf'],
  },
  {
    id: 'sp-11',
    kind: 'spark',
    author: 'nyra',
    date: '2026-09-18T20:09:00Z',
    reactions: 1288,
    comments: 51,
    text: 'Share cards are the cheapest growth loop we have. If your export looks like a screenshot, you get zero. If it looks like a poster, people tag you in it.',
    tags: ['design', 'growth'],
    media: [{ url: '/art/story-canvas.jpg', alt: 'Story share cards' }],
  },
  {
    id: 'sp-12',
    kind: 'spark',
    author: 'amara',
    date: '2026-09-18T10:40:00Z',
    reactions: 660,
    comments: 22,
    text: 'Type note for the day: line-height should TIGHTEN as size grows. Headings at 1.14, body at 1.78. Most systems do the reverse and it is why large text looks amateur.',
    tags: ['typography'],
  },
  {
    id: 'sp-13',
    kind: 'spark',
    author: 'sena',
    date: '2026-09-17T17:33:00Z',
    reactions: 512,
    comments: 40,
    text: 'Deleted the streak leaderboard today. Badge farming dropped to zero overnight and median session quality went up. Metrics you compare are metrics you corrupt.',
    tags: ['gamification'],
  },
  {
    id: 'sp-14',
    kind: 'spark',
    author: 'tobi',
    date: '2026-09-17T08:15:00Z',
    reactions: 388,
    comments: 19,
    text: 'Postgres note: putting long-form bodies in JSONB is free until the payload crosses 8KB and PostgreSQL starts decompressing TOAST during your feed sort. Keep feeds relational, pull articles by id, stay boring, stay fast.',
    tags: ['postgres', 'perf'],
  },
  {
    id: 'sp-15',
    kind: 'spark',
    author: 'devon',
    date: '2026-09-16T22:58:00Z',
    reactions: 1104,
    comments: 58,
    text: 'Heated a forge at 2am about thermodynamic ranking. Woke up and the author had quoted me in a comment with a counter-argument. This is the highest-leverage two seconds of my month.',
    tags: ['community'],
  },
  {
    id: 'sp-16',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-16T12:00:00Z',
    reactions: 2050,
    comments: 168,
    reposts: 290,
    text: 'We are not building a shorter Medium or a longer X. We are removing the wall between them: a 280-character spark and a 2,000-word forge live in the same feed, the same ranking maths, the same heat.\n\nIf you want the deep thing, you never get bounced to a stranger’s website to find it.',
    tags: ['vision'],
    media: [{ url: '/art/hero-forge.jpg', alt: 'A forge cover, lit from below' }],
  },
];
